### ISSUE TITLE
Using Capn' Proto or Flatbuffers for Storage 

### ISSUE THREAD

**Issue by Latrasis** [paritytech/wasm-tests#1]
Hello, @NikVolf! Any thoughts on using Capn' Proto (Or Flatbuffers) for In-Memory Representation on Storage? 

This would be advantageous in the same lines with https://github.com/shmookey/solpb.

**Comment by NikVolf** [comment]
Hi @Latrasis !

Not sure at what point you suggest to apply this exactly? Rust programs compiled into wasm are free to choose whatever they please to encode their data into storage primitives, including capnproto/protobuffer. The same holds for C/C++ or any other languages with wasm target.

**Comment by Latrasis** [comment]
Apologies, to elaborate - it's mainly an ergonomics question.

As you have noted, this is probably not relevant currently and probably too early to think about.
