### ISSUE TITLE
Automatic travis builds

### ISSUE THREAD

**Issue by NikVolf** [paritytech/wasm-tests#14]
1. should install emcc
2. should install `wasm32-unknown-emscripten` target
3. should use nightly rust
4. should invoke `./build.sh`
5. (discussable) should upload resulting wasm to repository `wasm-tests-binary`  ?

**Comment by lexfrl** [comment]
Can't use pre-built emcc in travis currently, see https://github.com/kripken/emscripten/pull/5087

**Comment by pepyakin** [comment]
I guess we can move this forward now.

**Comment by lexfrl** [comment]
guess so :)
